services:
  raft1:
    build: .
    environment:
      - NODE_ID=node1
      - RAFT_ADDR=raft1:7000
      - BOOTSTRAP=true
      - HTTP_ADDR=:8080
    # 外部から直接アクセスしたい場合はポートマッピング
    ports:
      - "8081:8080"
    networks:
      raftnet:
        ipv4_address: 172.28.0.11
  
  raft2:
    build: .
    environment:
      - NODE_ID=node2
      - RAFT_ADDR=raft2:7000
      - JOIN_ADDR=http://raft1:8080
      - HTTP_ADDR=:8080
    depends_on:
      - raft1
    networks:
      raftnet:
        ipv4_address: 172.28.0.12

  raft3:
    build: .
    environment:
      - NODE_ID=node3
      - RAFT_ADDR=raft3:7000
      - JOIN_ADDR=http://raft1:8080
      - HTTP_ADDR=:8080
    depends_on:
      - raft1
    networks:
      raftnet:
        ipv4_address: 172.28.0.13

  raft4:
    build: .
    environment:
      - NODE_ID=node4
      - RAFT_ADDR=raft4:7000
      - JOIN_ADDR=http://raft1:8080
      - HTTP_ADDR=:8080
    depends_on:
      - raft1
    networks:
      raftnet:
        ipv4_address: 172.28.0.14

  raft5:
    build: .
    environment:
      - NODE_ID=node5
      - RAFT_ADDR=raft5:7000
      - JOIN_ADDR=http://raft1:8080
      - HTTP_ADDR=:8080
    depends_on:
      - raft1
    networks:
      raftnet:
        ipv4_address: 172.28.0.15

networks:
  raftnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
